language: node_js
node_js:
  - "8"
dist: trusty
sudo: false

addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable

branches:
  only:
    - master

cache:
  directories:
    - ~/.npm
    - node_modules

before_install:
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
  - npm install -g firebase-tools http-server

script:
  - npm run prettier:warn
  - ng lint
  - ng build --prod
  - nohup http-server ./dist/apps/fullswing -p 8080 &
  - npm run cypress:record:ci

after_success:
  - firebase deploy --token $FIREBASE_TOKEN
