language: node_js
node_js:
  - "8"
dist: trusty
sudo: false

branches:
  only:
    - master

cache:
  directories:
    - ~/.npm
    - node_modules

before_script:
  - npm install -g firebase-tools

script:
  - npm run cypress:record
  - npm run prettier:warn
  - ng lint
  - ng build --prod

after_success:
  - firebase deploy --token $FIREBASE_TOKEN
