export const chatUsers = [
  {
    id: 'aaa',
    name: 'Tom Brady',
    avatar: 'http://angular-material.fusetheme.com/assets/images/avatars/Harper.jpg',
    status: 'online',
    chatList: [],
  },
  {
    id: 'bbb',
    name: 'Peyton Manning',
    avatar: 'http://angular-material.fusetheme.com/assets/images/avatars/garry.jpg',
    status: 'online',
    chatList: [],
  },
  {
    id: 'ccc',
    name: 'Emma Brinkman',
    avatar: 'http://angular-material.fusetheme.com/assets/images/avatars/Christy.jpg',
    status: 'online',
    chatList: [],
  },
  {
    id: 'ddd',
    name: 'Jane Adams',
    avatar: 'http://angular-material.fusetheme.com/assets/images/avatars/jane.jpg',
    status: 'online',
    chatList: [],
  },
  {
    id: 'eee',
    name: 'Jake Roberts',
    avatar: 'http://angular-material.fusetheme.com/assets/images/avatars/Arnold.jpg',
    status: 'online',
    chatList: [],
  },
  {
    id: 'fff',
    name: 'Michael Scott',
    avatar: 'http://angular-material.fusetheme.com/assets/images/avatars/Shepard.jpg',
    status: 'online',
    chatList: [],
  },
  {
    id: 'ggg',
    name: 'Hannah King',
    avatar: 'http://angular-material.fusetheme.com/assets/images/avatars/Nancy.jpg',
    status: 'online',
    chatList: [],
  },
];
